### ISSUE TITLE
Ajouter l'index d'injection ou avoir une valeur négative 

### ISSUE THREAD

**Issue by YNK22** [342apps/teleinfokit#17]
Bonjour, je souhaite savoir s'il est possible d'avoir la valeur de la production injecté dans le réseau (elle est dispo sur le linky mais pas sur HA) ou alors avoir la consommation avec une valeur négative lorsque je produis plus que ce que je consomme.

Est ce que c'est possible avec le module tic ? Je suis sur la dernière version.

**Comment by nicop4** [comment]
Bonjour 

Sur le principe, toutes les données émises par le compteur sont envoyées par MQTT par le boitier. 

Pour voir tous ces messages MQTT vous pouvez utiliser une application comme [MQTT Explorer](http://mqtt-explorer.com/).  Cette lecture des messages MQTT est documentée sur le github du projet ici : https://github.com/342apps/teleinfokit/blob/main/doc/mqtt.md

Coté Home Assistant, je n'ai inclus dans l'auto-discovery que les principales valeurs pour ne pas surcharger (quasi) inutilement le nombre de données exploitées par HA, mais il est tout à fait possible de rajouter ces sensors.

Pour cela comme indiqué dans la documentation [ici](https://github.com/342apps/teleinfokit/blob/main/doc/configuration-ha.md) il faut déclarer manuellement des sensors dans la configuration de home assistant :

Par exemple, pour les valeurs d'intensités des compteurs triphasé :

```yaml
mqtt:
  sensor:
    - state_topic: « teleinfokit-xxxxx/data/irms2"
      unique_id: teleinfokit_irms2
      unit_of_measurement: "A"
      device_class: current
      name: Intensité phase 2
      icon: mdi:power-plug
    - state_topic: « teleinfokit-xxxxx/data/irms3"
      unique_id: teleinfokit_irms3
      unit_of_measurement: "A"
      device_class: current
      name: Intensité phase 3
      icon: mdi:power-plug
```

Bien sur avec xxxxx a remplacer par l'id de votre boitier et le topic correspondant à l'étiquette que vous voulez.
